### ISSUE TITLE
Discord Keeps Crashing on newest version.[Bug]

### ISSUE THREAD

**Issue by ItzNxthaniel** [JsSucks/BetterDiscordApp#366] opened 2019-11-14 04:23 UTC
- [ ] Used appropriate template for the issue type
- [ ] Searched both open and closed issues for duplicates of this issue
- [ ] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**

**Additional context**

**Are you willing and able to fix this?**

**Comment by zerebos** [comment] 2019-11-14 04:33
Duplicate of #342

**Closed as completed by zerebos** 2019-11-14 04:33 UTC
Labels: bug
