### ISSUE TITLE
[Bug] crash when hover

### ISSUE THREAD

**Issue by KisaragiEffective** [JsSucks/BetterDiscordApp#359] opened 2019-07-20 16:15 UTC
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**
when hover, client crashes 100% (10/10, in my just hover test)

**To Reproduce**
Just hover server or buttons or material that shows additional text when mouse cursor is on it.

**Expected behavior**
doesn't crash

**Screenshots**
None

**System information**
Windows 7 x64, Official client@stable branch, bd 0.3.0x64

**Additional context**
nope

**Are you willing and able to fix this?**
no, c and c++ and js is difficult 4 me

**Comment by zerebos** [comment] 2019-07-20 16:43
Duplicate of #342

**Closed as completed by zerebos** 2019-07-20 16:43 UTC
Labels: bug
