### ISSUE TITLE
Can't make $npm run release

### ISSUE THREAD

**Issue by sws33** [JsSucks/BetterDiscordApp#261] opened 2018-11-25 16:33 UTC
ERROR in ../node_modules/mksnapshot/lib/mksnapshot-call.js
Module not found: Error: Can't resolve 'child_process' in '/home/vvs/install/betterdiscord/node_modules/mksnapshot/lib'
 @ ../node_modules/mksnapshot/lib/mksnapshot-call.js 8:10-34
 @ ../node_modules/mksnapshot/lib/main.js
 @ ../node_modules/asar/lib/snapshot.js
 @ ../node_modules/asar/lib/asar.js
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js

ERROR in ../node_modules/asar/lib/asar.js
Module not found: Error: Can't resolve 'original-fs' in '/home/vvs/install/betterdiscord/node_modules/asar/lib'
 @ ../node_modules/asar/lib/asar.js 2:39-61
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js

ERROR in ../node_modules/asar/lib/filesystem.js
Module not found: Error: Can't resolve 'original-fs' in '/home/vvs/install/betterdiscord/node_modules/asar/lib'
 @ ../node_modules/asar/lib/filesystem.js 2:39-61
 @ ../node_modules/asar/lib/asar.js
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js

ERROR in ../node_modules/asar/lib/disk.js
Module not found: Error: Can't resolve 'original-fs' in '/home/vvs/install/betterdiscord/node_modules/asar/lib'
 @ ../node_modules/asar/lib/disk.js 2:39-61
 @ ../node_modules/asar/lib/asar.js
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js

ERROR in ../node_modules/asar/lib/crawlfs.js
Module not found: Error: Can't resolve 'original-fs' in '/home/vvs/install/betterdiscord/node_modules/asar/lib'
 @ ../node_modules/asar/lib/crawlfs.js 2:39-61
 @ ../node_modules/asar/lib/asar.js
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js

ERROR in ../node_modules/asar/lib/snapshot.js
Module not found: Error: Can't resolve 'original-fs' in '/home/vvs/install/betterdiscord/node_modules/asar/lib'
 @ ../node_modules/asar/lib/snapshot.js 2:39-61
 @ ../node_modules/asar/lib/asar.js
 @ ./src/modules/packageinstaller.js
 @ ./src/modules/modules.js
 @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bdclient@2.0.0-b release: `webpack --progress --colors --config=webpack.production.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bdclient@2.0.0-b release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vvs/.npm/_logs/2018-11-25T16_19_28_034Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! betterdiscord@2.0.0-a build_release: `npm run release --prefix client && npm run build --prefix core && npm run release --prefix csseditor`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the betterdiscord@2.0.0-a build_release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vvs/.npm/_logs/2018-11-25T16_19_28_078Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! betterdiscord@2.0.0-a release: `npm run lint && npm run build_release && gulp release && npm run package_release`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the betterdiscord@2.0.0-a release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vvs/.npm/_logs/2018-11-25T16_19_28_126Z-debug.log

npm --version
6.4.1

**Comment by rauenzi** [comment] 2018-11-25 16:38
This is a duplicate of #259

**Closed** 2019-03-27 15:23 UTC
Labels: duplicate
