### ISSUE TITLE
[Bug] "A JavaScript error occured in the main process"

### ISSUE THREAD

**Issue by JonathinR** [JsSucks/BetterDiscordApp#371] opened 2020-03-04 22:49 UTC
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

![image](https://user-images.githubusercontent.com/41659379/75929705-02fb1900-5e26-11ea-989f-64ab4660984b.png)

For one, I am not on a 32-bit version of windows. Secondly, I have reason to believe this an issue with BT's dependency on Node Sass.

**To Reproduce**
1. Install either Discord or Discord PTB
2. Login
3. Install the latest release of BetterDiscord
4. Encounter error

**Expected behavior**
I expected to be able to use the software.

**System information**
- Windows 10 Pro (64-Bit, Version 1909, OS Build 18363.657)
- Branch-agnostic

**Are you willing and able to fix this?**
- Willing: Yes, provided that I had the knowledge on how to (of which I don't)
- Able to: No

**Comment by zerebos** [comment] 2020-03-04 22:51
Duplicate of #368

**Closed as completed by zerebos** 2020-03-04 22:51 UTC
Labels: bug
