### ISSUE TITLE
BetterDiscord V2 Keeps Crashing

### ISSUE THREAD

**Issue by Ixve** [JsSucks/BetterDiscordApp#361] opened 2019-09-22 20:09 UTC
I installed a few minutes ago BDV2 but I keep crashing whenever I hover over something, I'll uninstall until then but please give me a fix.

Windows 7 64-bit -- I'll use Bandaged BD until then.

**Comment by zerebos** [comment] 2019-09-22 20:12
Duplicate of #342 

Please do use BandagedBD this is not ready for non-developers.

**Closed as completed by zerebos** 2019-09-22 20:12 UTC
Labels: bug
