### ISSUE TITLE
[Bug] Crashes every time I open discord.

### ISSUE THREAD

**Issue by LiterallyCJ-ALT** [JsSucks/BetterDiscordApp#348] opened 2019-05-18 16:16 UTC
Describe the bug
When I open Discord up, it crashes.

To Reproduce
Open up discord with BD installed.
Instantly crashes upon opening.

System information
Windows 10 x64 1803. Newest version of BetterDiscord found here.

Are you willing and able to fix this?
No.

**Comment by Margen67** [comment] 2019-05-24 09:09
Duplicate of #342?

**Comment by alexklann** [comment] 2019-06-22 17:40
It is still crashing for me tho

**Comment by zerebos** [comment] 2019-06-22 17:45
Yes but it is still a duplicate.

**Closed as completed by zerebos** 2019-06-22 17:45 UTC
Labels: bug
