### ISSUE TITLE
[Bug] Latest release instantly crashes discord

### ISSUE THREAD

**Issue by LeagueRaINi** [JsSucks/BetterDiscordApp#362] opened 2019-09-26 13:32 UTC
**Describe the bug**
Latest BetterDiscord release instantly crashes discord (tested on 2 systems)

**To Reproduce**
Download and install the latest release (Beta 6)

**Expected behavior**
I expected BetterDiscord to work

**Screenshots**
![screenshot](https://i.imgur.com/3auxnf9.png)

**System information**
OS: Windows 10 1903 x64
Discord Branch: Stable (0.0.305)

**Additional context**
Probably related to https://github.com/JsSucks/BetterDiscordApp/issues/342 cause the fix from "Venipa" works just fine

**Are you willing and able to fix this?**
no.

**Comment by zerebos** [comment] 2019-09-26 13:33
This version is __not for users__ please continue to use BandagedBD. Duplicate of #342

**Closed as completed by zerebos** 2019-09-26 13:33 UTC
Labels: bug

**Comment by LeagueRaINi** [comment] 2019-09-26 13:37
Im aware that this is still under development but why make a release that doesnt work and not push a fix thats been made months ago?

**Comment by zerebos** [comment] 2019-09-26 14:14
The release worked at the time of release. It has not been fixed as the maintainer of this repo is quite busy.

**Comment by Kyza** [comment] 2019-09-26 14:22
At this point, if people are willing to actively maintain it, the repo should be forked and pushes should go there. Similarly to BBD. At least until Jiiks isn't busy anymore and decides to come back to development. Once that happens (if it does) the fork could be merged with this repo once again.

Unless Jiiks asked anyone to not do this, that is.

**Comment by zerebos** [comment] 2019-09-26 14:25
I can merge PRs into this repo, but the fix is just one commit in a very large PR beyond my scope of this repo. Most of that PR needs review by Jiiks since it touches their code. I did tell Sam I could merge the fix if it was separated out into its own PR.

![Quote](https://cdn.discordapp.com/attachments/341062370627682315/626786369959755796/unknown.png)
