### ISSUE TITLE
[Bug] Discord keeps crashing

### ISSUE THREAD

**Issue by Aholicknight** [JsSucks/BetterDiscordApp#353] opened 2019-06-08 19:41 UTC
Discord keeps crashing whenever I start it. I'm on the [Beta 6](https://github.com/JsSucks/BetterDiscordApp/releases/tag/2.0.0-beta.6) download. Everytime I start the program, it would work perfectly then crash. Any fixes?

**Comment by zerebos** [comment] 2019-06-08 23:07
Duplicate of #342

**Closed as completed by zerebos** 2019-06-08 23:07 UTC
Labels: bug
